### ISSUE TITLE
Шо за хрень, Олег.

### ISSUE THREAD

**Issue by ghost** [olegchir/freeasinfreedom-ru#5]
https://t.me/razbor_poletov_chat/61052
> ![image](https://user-images.githubusercontent.com/51895285/59574018-1eaa6d80-90a5-11e9-8b0e-54321d215597.png)

https://t.me/razbor_poletov_chat/61080
> ![image](https://user-images.githubusercontent.com/51895285/59574048-46013a80-90a5-11e9-8f2c-89e047e99a4f.png)

![image](https://user-images.githubusercontent.com/51895285/59574100-7f39aa80-90a5-11e9-8426-ae8b1c741d0f.png)

Олег, шо за хрень?

**Comment by ghost** [comment]
Шо за хрень, Олег?

**Comment by olegchir** [comment]
Works as intended
